import json

# Load notebook
with open('adversarial_demo.ipynb', 'r') as f:
    notebook = json.load(f)

# Update the image comparison cell to show improvement percentage
for i, cell in enumerate(notebook['cells']):
    if cell['cell_type'] == 'code' and 'source' in cell:
        source_text = ''.join(cell['source'])
        
        # Update the visual comparison cell
        if 'Defense Comparison:' in source_text and 'plt.suptitle' in source_text:
            cell['source'] = [
                "# Load all defense versions of the adversarial image\n",
                "fig, axes = plt.subplots(2, 3, figsize=(18, 12))\n",
                "axes = axes.flatten()\n",
                "\n",
                "# Prepare images and similarity scores\n",
                "images = []\n",
                "titles = []\n",
                "similarities = []\n",
                "\n",
                "# Baseline for improvement calculation\n",
                "baseline_drop = clean_sim - adv_sim\n",
                "\n",
                "# 1. Original adversarial image\n",
                "adv_img = Image.open(adv_path).convert(\"RGB\")\n",
                "images.append(adv_img)\n",
                "titles.append(\"Adversarial (No Defense)\")\n",
                "similarities.append(adv_sim)\n",
                "\n",
                "# 2-4. JPEG defenses (q=75, 50, 30)\n",
                "for quality in ['75', '50', '30']:\n",
                "    if 'jpeg_paths' in example and quality in example['jpeg_paths']:\n",
                "        jpeg_path = os.path.join(\"mmeb_eval_attacked\", example['jpeg_paths'][quality])\n",
                "        if os.path.exists(jpeg_path):\n",
                "            jpeg_img = Image.open(jpeg_path).convert(\"RGB\")\n",
                "            jpeg_sim = evaluate_similarity(model, preprocess, jpeg_path, example['text'], device)\n",
                "            images.append(jpeg_img)\n",
                "            titles.append(f\"JPEG (q={quality})\")\n",
                "            similarities.append(jpeg_sim)\n",
                "\n",
                "# 5. MAT defense (if available)\n",
                "if mat_model is not None:\n",
                "    images.append(adv_img)  # Same image, different model\n",
                "    titles.append(\"MAT Model Defense\")\n",
                "    mat_adv_sim = evaluate_similarity(mat_model, mat_preprocess, adv_path, example['text'], device)\n",
                "    similarities.append(mat_adv_sim)\n",
                "\n",
                "# 6. PGD defense (if available)\n",
                "if pgd_model is not None:\n",
                "    images.append(adv_img)  # Same image, different model\n",
                "    titles.append(\"PGD Model Defense\")\n",
                "    pgd_adv_sim = evaluate_similarity(pgd_model, pgd_preprocess, adv_path, example['text'], device)\n",
                "    similarities.append(pgd_adv_sim)\n",
                "\n",
                "# Plot all images\n",
                "for i, (img, title, sim) in enumerate(zip(images, titles, similarities)):\n",
                "    if i < len(axes):\n",
                "        axes[i].imshow(img)\n",
                "        \n",
                "        # Calculate improvement\n",
                "        defense_drop = clean_sim - sim\n",
                "        improvement = ((baseline_drop - defense_drop) / baseline_drop * 100) if baseline_drop > 0 else 0\n",
                "        \n",
                "        status = \"✓\" if sim > 0 else \"✗\"\n",
                "        color = 'green' if sim > 0 else 'red'\n",
                "        \n",
                "        # Add improvement percentage to title\n",
                "        if i == 0:  # Adversarial baseline\n",
                "            axes[i].set_title(f\"{title}\\nSimilarity: {sim:+.4f} {status}\", \n",
                "                             fontsize=11, color=color, weight='bold')\n",
                "        else:\n",
                "            axes[i].set_title(f\"{title}\\nSim: {sim:+.4f} {status} | Recovery: {improvement:+.1f}%\", \n",
                "                             fontsize=10, color=color, weight='bold')\n",
                "        axes[i].axis('off')\n",
                "\n",
                "# Hide empty subplots\n",
                "for i in range(len(images), len(axes)):\n",
                "    axes[i].axis('off')\n",
                "\n",
                "plt.suptitle(f'Defense Comparison: \"{example[\"text\"]}\"', \n",
                "             fontsize=14, weight='bold', y=0.98)\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Print summary\n",
                "print(\"\\n\" + \"=\"*80)\n",
                "print(\"Image Comparison Summary\")\n",
                "print(\"=\"*80)\n",
                "for title, sim in zip(titles, similarities):\n",
                "    defense_drop = clean_sim - sim\n",
                "    improvement = ((baseline_drop - defense_drop) / baseline_drop * 100) if baseline_drop > 0 else 0\n",
                "    status = \"✓ DEFENDED\" if sim > 0 else \"✗ BROKEN\"\n",
                "    print(f\"{title:<30} Sim: {sim:+.4f}  {status:<12} Improvement: {improvement:+.1f}%\")\n",
                "print(\"=\"*80)"
            ]
            cell['outputs'] = []
            cell['execution_count'] = None
            print("✓ Updated image comparison cell with improvement percentages")
        
        # Update the bar chart to include all JPEG versions
        elif 'Visualize defense comparison' in source_text and 'bars1' in source_text:
            cell['source'] = [
                "# Visualize defense comparison with all JPEG versions\n",
                "defense_methods = ['Original', 'JPEG q=75', 'JPEG q=50', 'JPEG q=30', 'MAT', 'PGD']\n",
                "clean_scores_all = []\n",
                "adv_scores_all = []\n",
                "\n",
                "# Original\n",
                "clean_scores_all.append(clean_sim)\n",
                "adv_scores_all.append(adv_sim)\n",
                "\n",
                "# JPEG defenses\n",
                "for quality in ['75', '50', '30']:\n",
                "    if 'jpeg_paths' in example and quality in example['jpeg_paths']:\n",
                "        jpeg_path = os.path.join(\"mmeb_eval_attacked\", example['jpeg_paths'][quality])\n",
                "        if os.path.exists(jpeg_path):\n",
                "            jpeg_sim = evaluate_similarity(model, preprocess, jpeg_path, example['text'], device)\n",
                "            clean_scores_all.append(clean_sim)  # JPEG doesn't affect clean\n",
                "            adv_scores_all.append(jpeg_sim)\n",
                "        else:\n",
                "            clean_scores_all.append(0)\n",
                "            adv_scores_all.append(0)\n",
                "    else:\n",
                "        clean_scores_all.append(0)\n",
                "        adv_scores_all.append(0)\n",
                "\n",
                "# MAT\n",
                "if mat_model is not None:\n",
                "    clean_scores_all.append(results.get('MAT', {}).get('clean', 0))\n",
                "    adv_scores_all.append(results.get('MAT', {}).get('adv', 0))\n",
                "else:\n",
                "    clean_scores_all.append(0)\n",
                "    adv_scores_all.append(0)\n",
                "\n",
                "# PGD\n",
                "if pgd_model is not None:\n",
                "    clean_scores_all.append(results.get('PGD', {}).get('clean', 0))\n",
                "    adv_scores_all.append(results.get('PGD', {}).get('adv', 0))\n",
                "else:\n",
                "    clean_scores_all.append(0)\n",
                "    adv_scores_all.append(0)\n",
                "\n",
                "# Filter out zeros (methods not available)\n",
                "valid_indices = [i for i, (c, a) in enumerate(zip(clean_scores_all, adv_scores_all)) if c != 0 or a != 0]\n",
                "methods_filtered = [defense_methods[i] for i in valid_indices]\n",
                "clean_filtered = [clean_scores_all[i] for i in valid_indices]\n",
                "adv_filtered = [adv_scores_all[i] for i in valid_indices]\n",
                "\n",
                "x = np.arange(len(methods_filtered))\n",
                "width = 0.35\n",
                "\n",
                "fig, ax = plt.subplots(figsize=(14, 7))\n",
                "bars1 = ax.bar(x - width/2, clean_filtered, width, label='Clean', color='green', alpha=0.7)\n",
                "bars2 = ax.bar(x + width/2, adv_filtered, width, label='Adversarial', color='red', alpha=0.7)\n",
                "\n",
                "ax.set_ylabel('Similarity Score', fontsize=12)\n",
                "ax.set_title('Defense Effectiveness: Clean vs. Adversarial Similarity', fontsize=14, weight='bold')\n",
                "ax.set_xticks(x)\n",
                "ax.set_xticklabels(methods_filtered, rotation=20, ha='right', fontsize=11)\n",
                "ax.legend(fontsize=11)\n",
                "ax.axhline(y=0, color='black', linestyle='--', alpha=0.3, linewidth=1.5)\n",
                "ax.grid(axis='y', alpha=0.3)\n",
                "\n",
                "# Add value labels\n",
                "for bars in [bars1, bars2]:\n",
                "    for bar in bars:\n",
                "        height = bar.get_height()\n",
                "        if height != 0:  # Only label non-zero bars\n",
                "            ax.text(bar.get_x() + bar.get_width()/2., height,\n",
                "                    f'{height:.3f}',\n",
                "                    ha='center', va='bottom' if height > 0 else 'top', fontsize=9)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
            cell['outputs'] = []
            cell['execution_count'] = None
            print("✓ Updated bar chart to include all JPEG versions")

# Save notebook
with open('adversarial_demo.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("✓ Notebook updated successfully!")
